---
- name: Import Vagrant host variables
  include_vars:
    file: "{{ playbook_dir }}/vagrant_hosts.yml"

- name: Halt Vagrant boxes
  include_tasks: "vagrant_halt.yml"
  with_items: "{{ vagrant_host_list }}"
  when: (taskname == "vagrant_up") and (taskname is defined)

- name: Destroy Vagrant boxes
  include_tasks: "vagrant_destroy.yml"
  with_items: "{{ vagrant_host_list }}"
  when: (taskname == "vagrant_up") and (taskname is defined)

- name: Generate Vagrantfile and config.yml
  include_tasks: vagrant_generate_files.yml
  with_items: "{{ vagrant_host_list }}"
  when: (taskname == "vagrant_up") and (taskname is defined)

- name: Start Vagrant boxes
  include_tasks: "vagrant_up.yml"
  with_items: "{{ vagrant_host_list }}"
  when: (taskname == "vagrant_up") and (taskname is defined)
...
